// src/controllers/adminController.js
const User = require('../models/User');
const Doctor = require('../models/Doctor');
const Patient = require('../models/Patient');
const Appointment = require('../models/Appointment');
const Symptom = require('../models/Symptom');
const SymptomMapping = require('../models/SymptomMapping');
const emailService = require('../services/emailService');
const { generateRandomPassword, generateUserId } = require('../utils/generatePassword');
const crypto = require('crypto');


// Create doctor (admin only)
// exports.createDoctor = async (req, res) => {
//   try {
//     const { name, email, phone, specialization, qualification, experience, consultationFee, treatsSymptoms } = req.body;
    
//     // Check if user exists
//     let user = await User.findOne({ email });
//     if (user) {
//       return res.status(400).json({ success: false, message: 'User already exists' });
//     }
    
//     const password = generateRandomPassword();
    
//     // Create user
//     user = await User.create({
//       name,
//       email,
//       password,
//       phone,
//       role: 'doctor'
//     });
    
//     // Create doctor profile
//     const doctor = await Doctor.create({
//       userId: user._id,
//       specialization,
//       qualification,
//       experience,
//       consultationFee,
//       treatsSymptoms: treatsSymptoms || []
//     });
    
//     // Send credentials via email
//     await emailService.sendDoctorCredentials(email, name, user._id, password);
    
//     res.status(201).json({
//       success: true,
//       message: 'Doctor created successfully',
//       doctor: {
//         id: doctor._id,
//         user: {
//           id: user._id,
//           name: user.name,
//           email: user.email
//         },
//         specialization,
//         consultationFee
//       }
//     });
//   } catch (error) {
//     res.status(500).json({ success: false, message: error.message });
//   }
// };
// Create doctor with auto-generated password
exports.createDoctor = async (req, res) => {
  try {
    const {
      name, email, phone, specialization, qualification,
      experience, consultationFee, treatsSymptoms, bio, clinicAddress
    } = req.body;
    
    // Check if user already exists
    let existingUser = await User.findOne({ email });
    if (existingUser) {
      return res.status(400).json({ success: false, message: 'Email already exists' });
    }
    
    // Generate password and user ID
    const password = generateRandomPassword(10);
    const userId = generateUserId(name, 'doctor');
    
    // Create user
    const user = await User.create({
      name,
      email,
      password,
      phone,
      role: 'doctor',
      isActive: true
    });
    
    // Create doctor profile
    const doctor = await Doctor.create({
      userId: user._id,
      specialization,
      qualification,
      experience: experience || 0,
      consultationFee,
      treatsSymptoms: treatsSymptoms || [],
      bio: bio || '',
      clinicAddress: clinicAddress || ''
    });
    
    // Send credentials via email
    await emailService.sendDoctorCredentials(email, name, user._id, password);
    
    res.status(201).json({
      success: true,
      message: 'Doctor created successfully. Credentials sent to email.',
      data: {
        doctorId: doctor._id,
        userId: user._id,
        name: user.name,
        email: user.email,
        specialization: doctor.specialization,
        consultationFee: doctor.consultationFee,
        autoGeneratedPassword: password // Remove in production
      }
    });
    
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Get all doctors
exports.getAllDoctors = async (req, res) => {
  try {
    const doctors = await Doctor.find().populate('userId', 'name email phone');
    res.json({ success: true, count: doctors.length, doctors });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Get all patients
exports.getAllPatients = async (req, res) => {
  try {
    const patients = await Patient.find().populate('userId', 'name email phone');
    res.json({ success: true, count: patients.length, patients });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Get all users
exports.getAllUsers = async (req, res) => {
  try {
    const users = await User.find().select('-password');
    res.json({ success: true, count: users.length, users });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Change user role
exports.changeUserRole = async (req, res) => {
  try {
    const { id } = req.params;
    const { role } = req.body;
    
    const user = await User.findByIdAndUpdate(id, { role }, { new: true });
    if (!user) {
      return res.status(404).json({ success: false, message: 'User not found' });
    }
    
    res.json({ success: true, message: 'Role updated successfully', user });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Block user
exports.blockUser = async (req, res) => {
  try {
    const { id } = req.params;
    const user = await User.findByIdAndUpdate(id, { isActive: false }, { new: true });
    
    if (!user) {
      return res.status(404).json({ success: false, message: 'User not found' });
    }
    
    res.json({ success: true, message: 'User blocked successfully' });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Unblock user
exports.unblockUser = async (req, res) => {
  try {
    const { id } = req.params;
    const user = await User.findByIdAndUpdate(id, { isActive: true }, { new: true });
    
    if (!user) {
      return res.status(404).json({ success: false, message: 'User not found' });
    }
    
    res.json({ success: true, message: 'User unblocked successfully' });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Admin dashboard stats
exports.getDashboardStats = async (req, res) => {
  try {
    const totalDoctors = await Doctor.countDocuments();
    const totalPatients = await Patient.countDocuments();
    const totalAppointments = await Appointment.countDocuments();
    const todayAppointments = await Appointment.countDocuments({
      date: {
        $gte: new Date().setHours(0, 0, 0),
        $lt: new Date().setHours(23, 59, 59)
      }
    });
    
    const revenue = await Appointment.aggregate([
      { $match: { paymentStatus: 'paid' } },
      { $group: { _id: null, total: { $sum: '$amount' } } }
    ]);
    
    res.json({
      success: true,
      stats: {
        totalDoctors,
        totalPatients,
        totalAppointments,
        todayAppointments,
        totalRevenue: revenue[0]?.total || 0
      }
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Get appointment report
exports.getAppointmentReport = async (req, res) => {
  try {
    const { startDate, endDate } = req.query;
    
    const query = {};
    if (startDate && endDate) {
      query.createdAt = {
        $gte: new Date(startDate),
        $lte: new Date(endDate)
      };
    }
    
    const appointments = await Appointment.find(query)
      .populate('patientId', 'name email')
      .populate('doctorId', 'specialization');
    
    const completed = appointments.filter(a => a.status === 'completed').length;
    const cancelled = appointments.filter(a => a.status === 'cancelled').length;
    const pending = appointments.filter(a => a.status === 'pending').length;
    
    res.json({
      success: true,
      report: {
        total: appointments.length,
        completed,
        cancelled,
        pending,
        appointments
      }
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Get revenue report
exports.getRevenueReport = async (req, res) => {
  try {
    const { startDate, endDate } = req.query;
    
    const query = { paymentStatus: 'paid' };
    if (startDate && endDate) {
      query.createdAt = {
        $gte: new Date(startDate),
        $lte: new Date(endDate)
      };
    }
    
    const appointments = await Appointment.find(query);
    const totalRevenue = appointments.reduce((sum, app) => sum + (app.amount || 0), 0);
    
    const monthlyRevenue = await Appointment.aggregate([
      { $match: query },
      {
        $group: {
          _id: { $month: '$createdAt' },
          total: { $sum: '$amount' },
          count: { $sum: 1 }
        }
      }
    ]);
    
    res.json({
      success: true,
      report: {
        totalRevenue,
        totalAppointments: appointments.length,
        monthlyRevenue
      }
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Get doctor performance report
exports.getDoctorPerformanceReport = async (req, res) => {
  try {
    const doctors = await Doctor.find().populate('userId', 'name');
    
    const performance = await Promise.all(doctors.map(async (doctor) => {
      const appointments = await Appointment.find({ doctorId: doctor._id });
      const completed = appointments.filter(a => a.status === 'completed').length;
      const totalRevenue = appointments
        .filter(a => a.paymentStatus === 'paid')
        .reduce((sum, a) => sum + (a.amount || 0), 0);
      
      return {
        doctorId: doctor._id,
        name: doctor.userId?.name,
        specialization: doctor.specialization,
        totalAppointments: appointments.length,
        completedAppointments: completed,
        totalRevenue,
        rating: doctor.rating
      };
    }));
    
    res.json({ success: true, performance });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Get all appointments (admin)
exports.getAllAppointments = async (req, res) => {
  try {
    const appointments = await Appointment.find()
      .populate('patientId', 'name email phone')
      .populate('doctorId', 'specialization')
      .sort('-createdAt');
    
    res.json({ success: true, count: appointments.length, appointments });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

